####################################################################################
#                                  Server                                          #
####################################################################################
server:
  port: 5656
  servlet:
    context-path: /demo-server
    encoding:
      # charset UTF-8 강제설정
      charset: UTF-8
      force: true
      enabled: true
  error:
    path: /error
    # always | never
    include-stacktrace: never
    whitelabel.enabled: false

jwt:
  token:
    header: X-Auth-Token
    secret: demo?auth?bp
    # 토큰 만료 시간 (1 day : 86400, 1 week 604800)
    expiration: 86400
    origin: demos
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
####################################################################################
#                                    DEFAULT                                       #
####################################################################################
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
  main:
    # 스프링 bean 오버라이드 허용
    allow-bean-definition-overriding: true
  profiles:
    active: loc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        # [물리] 스네이크 -> 카멜 케이스로 변경
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # [논리]
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    # JPA 실행 쿼리 표시
    #show-sql: true
    properties:
      hibernate:
        # 콘솔에 표시되는 쿼리를 가독성 있게 표시
        format_sql: true
        # laze loading 전략 사용
        enable_lazy_load_no_trans: true
  # 멀티파츠 사이즈 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  # 세션 타입 설정
  session:
    store-type: jdbc

#### Custom 속성 ####
# 버전정보
demo:
  info:
    version: 1.0.0

---
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
####################################################################################
#                                    LOC                                           #
####################################################################################
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
  profiles: loc
  datasource:
    # always | embedded | never
    initialization-mode: always
    data: classpath:data.sql
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      # create | create-drop | none | update | validate
      ddl-auto: create-drop
    #jackson:
    # null인 데이터 제외
  #  default-property-inclusion: non_null